services:
  erp-integration:
    image: erp-integration
    restart: always
    ports:
      - "8081:8080"
    networks:
      - karavan
    environment:
      - ERP_USER=
      - ERP_PASSWORD=